#!/usr/bin/with-contenv bash

mkdir -p /config

# copy the default smb.conf file to external config folder if not present
if [ ! -f /config/smb.conf ]; then
    sed -i "s/workgroup = MYGROUP/workgroup = WORKGROUP/g" /etc/samba/smb.conf && \
    sed -i "s/server string = Samba Server/server string = Homeserver Samba/g" /etc/samba/smb.conf && \
    echo "[share]" >> /etc/samba/smb.conf && \
    echo "   path = /share" >> /etc/samba/smb.conf && \
    echo "   public = yes" >> /etc/samba/smb.conf && \
    echo "   read only = yes" >> /etc/samba/smb.conf && \
    echo "   only guest = yes" >> /etc/samba/smb.conf && \
    echo "   guest account = abc" >> /etc/samba/smb.conf
    cp /etc/samba/smb.conf /config/smb.conf
    
fi

chown -R abc:abc /config
