version: "3"
services:
  minecraft:
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    volumes:
      - /config/minecraft:/config
      - /dynmap_data:/dynmap_data
    environment:
      - EULA=true
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  samba:
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share:ro
      - /mnt/usb/temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    network_mode: host
    container_name: transmission
    volumes:
      - /config/transmission:/config
      - /mnt/usb/media:/downloads
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/transmission-web-control
    restart: unless-stopped

  nginx:
    build: ./nginx
    network_mode: host
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/nginx:/config
      - /config/minecraft/plugins/dynmap/web:/dynmap:ro
      - /dynmap_data:/dynmap_data:ro
    restart: unless-stopped

  rclone:
    image: pfidr/rclone
    container_name: rclone
    environment:
      - SYNC_SRC=/source
      - SYNC_DEST=gdrive:homeserver
      - CRON=0 3 * * *
      - FORCE_SYNC=1
      - TZ=America/New_York
      - UID=1000
      - GID=1000
      - CHECK_URL=https://hc-ping.com/e7c29a0a-dd5a-4c63-8db7-7bdc40faf3ea
    volumes:
      - /rclone:/config
      - /config:/source:ro
    restart: unless-stopped

  homeassistant: # 9999/tcp 5353/udp 51827/tcp
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - PACKAGES=iputils
    volumes:
      - /config/homeassistant:/config
      - /config/homeassistant/docker/run:/etc/services.d/home-assistant/run:ro
    restart: unless-stopped

  jellyfin: # 8096/tcp
    image: linuxserver/jellyfin
    network_mode: host
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/jellyfin:/config
      - /mnt/usb/media/tvshows:/data/tvshows:ro
      - /mnt/usb/media/movies:/data/movies:ro
      - /transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  
  unbound: # localhost 5335/udp
    build: ./unbound
    network_mode: host
    container_name: unbound
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/unbound:/config
    restart: unless-stopped
  
  # for HomeKit and Samba's mDNS service
  avahi: # 5353/udp
    build: ./avahi
    container_name: avahi
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/avahi:/config
      - /config/avahi/services:/etc/avahi/services:ro
    restart: unless-stopped
