version: "3"
services:
  minecraft:
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    volumes:
      - /config/minecraft:/config
    environment:
      - EULA=true
    restart: unless-stopped
  
  samba:
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share:ro
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    network_mode: host
    container_name: transmission
    volumes:
      - /config/transmission:/config
      - /mnt/usb/media:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/transmission-web-control
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    network_mode: host
    container_name: nginx
    volumes:
      - /config/nginx:/config
    restart: unless-stopped

  rclone:
    image: pfidr/rclone
    container_name: rclone
    environment:
      - SYNC_SRC=/source
      - SYNC_DEST=gdrive:homeserver
      - CRON="0 3 * * *"
      - FORCE_SYNC=1
      - TZ=America/New_York
      - CHECK_URL=https://hc-ping.com/e7c29a0a-dd5a-4c63-8db7-7bdc40faf3ea
    volumes:
      - /rclone:/config
      - /config:/source:ro
    restart: unless-stopped
