version: "3"
services:
  minecraft:
    build: ./minecraft
    network_mode: host
    container_name: minecraft-spigot
    volumes:
      - /config/minecraft:/config
    environment:
      - EULA=true
    restart: unless-stopped