version: "3"
services:
  # unbound & pihole for providing DNS services
  unbound: # 127.0.0.1:5335/udp
    build: ./unbound
    network_mode: host
    container_name: unbound
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/unbound:/config
    restart: unless-stopped
  
  pihole: # *:53 127.0.0.1:5000
    container_name: pihole
    # official pihole docker lacks PUID and PGID
    # track https://github.com/pi-hole/docker-pi-hole/issues/328 for news
    # so we apply various patches to the official pihole image to make some customizations
    # so that the config files' permissions are not messed up and setupvars won't be overriden 
    # everytime the container restarts
    build: ./pihole
    depends_on: 
      - unbound
    network_mode: host
    environment:
      - TZ='America/New_York'
      - WEB_PORT=5000
      - ServerIP=127.0.0.1
      - DNSMASQ_LISTENING=enp12s0
      - INTERFACE=enp12s0
      - DNSMASQ_USER=pihole
    volumes:
      - /config/pihole/pihole:/etc/pihole/
      - /config/pihole/dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped

  # minecraft server (PaperMC) with plugins
  minecraft: # *:25565/tcp 127.0.0.1:25564/tcp 127.0.0.1:9999/tcp
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    depends_on: 
      - pihole  # needs pihole to resolve DNS to download papermc.
    volumes:
      - /config/minecraft:/config
    environment:
      - EULA=true
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  samba: # 445/tcp
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share:ro
      - /mnt/usb/temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  # for Samba's mDNS service
  avahi: # 5353/udp
    depends_on: 
      - samba
    build: ./avahi
    container_name: avahi
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/avahi:/config
      - /config/avahi/services:/etc/avahi/services:ro
    restart: unless-stopped

  transmission: # 127.0.0.1:9091 *:51413
    image: ghcr.io/linuxserver/transmission
    network_mode: host
    container_name: transmission
    depends_on: 
      - pihole  # needs pihole to resolve DNS queries to get tracker address
    volumes:
      - /config/transmission:/config
      - /mnt/usb/media:/downloads
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  nginx: # reverse proxy
    build: ./nginx
    network_mode: host
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/nginx:/config
      - /config/minecraft/plugins/BlueMap/web:/bluemap:ro  # for bluemap
    restart: unless-stopped

  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    depends_on: 
      - pihole  # needs pihole to resolve DNS queries for external drives (e.g., google drive)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/duplicati:/config
      - /config:/source
    ports:
      - 127.0.0.1:8200:8200
    restart: unless-stopped

  homeassistant: # 127.0.0.1:9999/tcp *:5353/udp *:51827/tcp
    image: homeassistant/home-assistant:2020.12.0
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - PACKAGES=iputils
    volumes:
      - /config/homeassistant:/config
      - /config/homeassistant/docker/run:/etc/services.d/home-assistant/run:ro
    restart: unless-stopped

  jellyfin: # 127.0.0.1:8096/tcp
    image: ghcr.io/linuxserver/jellyfin
    network_mode: host
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/jellyfin:/config
      - /mnt/usb/media/tvshows:/data/tvshows:ro
      - /mnt/usb/media/movies:/data/movies:ro
      - /transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    depends_on: 
      - pihole  # needs pihole to resolve DNS queries for the peers
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  