version: "3"
services:
  minecraft: # *:25565/tcp 127.0.0.1:25564/tcp 127.0.0.1:9999/tcp
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    volumes:
      - /config/minecraft:/config
      - /dynmap_data:/dynmap_data
    environment:
      - EULA=true
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  samba: # 445/tcp
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share:ro
      - /mnt/usb/temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  transmission: # 127.0.0.1:9091 *:51413
    image: linuxserver/transmission
    network_mode: host
    container_name: transmission
    volumes:
      - /config/transmission:/config
      - /mnt/usb/media:/downloads
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  nginx: # reverse proxy
    build: ./nginx
    network_mode: host
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/nginx:/config
      - /config/minecraft/plugins/dynmap/web:/dynmap:ro # for dynmap
      - /dynmap_data:/dynmap_data:ro # for dynmap
    restart: unless-stopped

  rclone:
    image: pfidr/rclone
    container_name: rclone
    environment:
      - SYNC_SRC=/source
      - SYNC_DEST=gdrive:homeserver
      - CRON=0 3 * * *
      - FORCE_SYNC=1
      - TZ=America/New_York
      - UID=1000
      - GID=1000
      - CHECK_URL=https://hc-ping.com/e7c29a0a-dd5a-4c63-8db7-7bdc40faf3ea
    volumes:
      - /rclone:/config
      - /config:/source:ro
    restart: unless-stopped

  homeassistant: # 127.0.0.1:9999/tcp *:5353/udp *:51827/tcp
    image: homeassistant/home-assistant:0.114.4
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - PACKAGES=iputils
    volumes:
      - /config/homeassistant:/config
      - /config/homeassistant/docker/run:/etc/services.d/home-assistant/run:ro
    restart: unless-stopped

  jellyfin: # 127.0.0.1:8096/tcp
    image: linuxserver/jellyfin
    network_mode: host
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/jellyfin:/config
      - /mnt/usb/media/tvshows:/data/tvshows:ro
      - /mnt/usb/media/movies:/data/movies:ro
      - /transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  
  unbound: # 127.0.0.1:5335/udp
    build: ./unbound
    network_mode: host
    container_name: unbound
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/unbound:/config
    restart: unless-stopped
  
  # for HomeKit and Samba's mDNS service
  avahi: # 5353/udp
    build: ./avahi
    container_name: avahi
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/avahi:/config
      - /config/avahi/services:/etc/avahi/services:ro
    restart: unless-stopped

  firefly:
    build: ./firefly
    container_name: firefly
    ports:
      - 127.0.0.1:7000:80
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/firefly:/config
    restart: unless-stopped
