version: "3"
services:
  # unbound & adguard for providing DNS services
  unbound: # 127.0.0.1:5335/udp
    build: ./unbound
    network_mode: host
    container_name: unbound
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/unbound:/config
    restart: unless-stopped
  
  adguard: # *:53 127.0.0.1:5000
    container_name: adguard
    image: adguard/adguardhome
    depends_on: 
      - unbound
    network_mode: host
    volumes:
      - /config/adguard/work:/opt/adguardhome/work
      - /config/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
  
  nginx: # reverse proxy
    build: ./nginx
    network_mode: host
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/nginx:/config
      - /config/minecraft/plugins/BlueMap/web:/bluemap:ro  # for bluemap
    restart: unless-stopped

  vaultwarden: 
    container_name: vaultwarden
    image: vaultwarden/server
    user: '1000:1000'
    depends_on:
      - adguard # needs adguard to resolve DNS for the service
      - nginx # needs nginx for reverse proxy
    volumes:
      - /config/vaultwarden:/data
    ports:
      - 127.0.0.1:3012:3012
      - 127.0.0.1:7777:80
    restart: unless-stopped

  # minecraft server (PaperMC) with plugins
  minecraft: # *:25565/tcp 127.0.0.1:25564/tcp 127.0.0.1:9999/tcp
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    depends_on: 
      - adguard  # needs adguard to resolve DNS to download papermc.
    volumes:
      - /config/minecraft:/config
    environment:
      - EULA=true
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  samba: # 445/tcp
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share:ro
      - /mnt/usb/media/books:/writable-books
      - /mnt/usb/temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  # for Samba's mDNS service
  avahi: # 5353/udp
    depends_on: 
      - samba
    build: ./avahi
    container_name: avahi
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/avahi:/config
      - /config/avahi/services:/etc/avahi/services:ro
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: host
    container_name: qbittorrent
    depends_on: 
      - adguard  # needs adguard to resolve DNS queries to get tracker address
      - nginx # needs nginx to reverse proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /config/qbittorrent:/config
      - /mnt/usb/media:/downloads
    restart: unless-stopped

  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    depends_on: 
      - adguard  # needs adguard to resolve DNS queries for external drives (e.g., google drive)
      - nginx # needs nginx to reverse proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/duplicati:/config
      - /config:/source
    ports:
      - 127.0.0.1:8200:8200
    restart: unless-stopped

  homeassistant: # 127.0.0.1:9999/tcp *:5353/udp *:51827/tcp
    image: ghcr.io/linuxserver/homeassistant
    depends_on: 
      - adguard  # needs adguard to resolve DNS queries for the service
      - nginx # needs nginx to reverse proxy
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/homeassistant:/config
    restart: unless-stopped

  jellyfin: # 127.0.0.1:8096/tcp
    image: ghcr.io/linuxserver/jellyfin
    depends_on: 
      - adguard  # needs adguard to resolve DNS queries for the service
      - nginx # needs nginx to reverse proxy
    network_mode: host
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    tmpfs:
      - /transcode
      - /cache
    volumes:
      - /config/jellyfin:/config
      - /mnt/usb/media/tvshows:/data/tvshows
      - /mnt/usb/media/movies:/data/movies
      - /mnt/usb/media/anime:/data/anime
      - /mnt/usb/media/music:/data/music
      - /mnt/usb/media/books:/data/books:ro
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    network_mode: host
    depends_on: 
      - adguard  # needs adguard to resolve DNS queries for the peers
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/wireguard:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
  
