version: "3"
services:
  minecraft:
    build: ./minecraft
    network_mode: host
    container_name: minecraft
    volumes:
      - /config/minecraft:/config
    environment:
      - EULA=true
    restart: unless-stopped
  
  samba:
    build: ./samba
    network_mode: host
    container_name: samba
    volumes:
      - /config/samba:/config
      - /mnt/usb/media:/share
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    network_mode: host
    container_name: transmission
    volumes:
      - /config/transmission:/config
      - /mnt/usb/media:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped