#!/usr/bin/with-contenv bash

mkdir -p /config

if [ ! -f /config/.env ]; then 
    cp ${FIREFLY_PATH}/.env /config/.env 
fi

rm ${FIREFLY_PATH}/.env

if [ ! -d /config/database ]; then
    cp -r ${FIREFLY_PATH}/storage/database /config/database
fi
rm -rf ${FIREFLY_PATH}/storage/database

if [ ! -d /config/upload ]; then
    cp -r ${FIREFLY_PATH}/storage/upload /config/upload
fi
rm -rf ${FIREFLY_PATH}/storage/upload

# map the files 
ln -s /config/.env ${FIREFLY_PATH}/.env
ln -s /config/database ${FIREFLY_PATH}/storage/database
ln -s /config/upload ${FIREFLY_PATH}/storage/upload

chown -R abc:abc /config