#!/usr/bin/with-contenv bash

# create config folder
mkdir -p /config

# copy the compiled plugins to config folder
mkdir -p /config/plugins

python3 /jar_updater.py /minecraft /config/plugins

# create world folder if not present
mkdir -p /config/world
